version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/srinivasa
      - EMAIL_USER=example@gmail.com
      - EMAIL_PASS=yourpassword

  admin-panel:
    build: ./admin-panel
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017" 